// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmJoVqtng7Hq8LzTR9MGfxCgBseoJL2Qk',
    appId: '1:836127824057:web:3c61b8a2943b800a00a368',
    messagingSenderId: '836127824057',
    projectId: 'neo-pos-6b9ed',
    authDomain: 'neo-pos-6b9ed.firebaseapp.com',
    storageBucket: 'neo-pos-6b9ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl6q808ka3PrAS9EU1klYXyazJmQGZRQY',
    appId: '1:836127824057:android:c1b720d4feae7d7d00a368',
    messagingSenderId: '836127824057',
    projectId: 'neo-pos-6b9ed',
    storageBucket: 'neo-pos-6b9ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9U8rgPCC_jtf5FMNwTvxtUYCG00mYkI',
    appId: '1:836127824057:ios:b12a1c8ee703406200a368',
    messagingSenderId: '836127824057',
    projectId: 'neo-pos-6b9ed',
    storageBucket: 'neo-pos-6b9ed.appspot.com',
    iosClientId:
        '836127824057-fr2pch5c4to7fbikeaibkqtkb68ev3ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.neopos',
  );
}
